### ISSUE TITLE
Please update "Transforming Delete, Retrieve, Generate Approach for Controlled Text Style Transfer" 

### ISSUE THREAD

**Issue by Bhargav5** [fuzhenxin/Style-Transfer-in-Text#10]
Hi,
I really appreciate your efforts on compiling all the research papers on text style transfer. Our paper "Transforming Delete, Retrieve, Generate Approach for Controlled Text
Style Transfer" (https://128.84.21.199/pdf/1908.09368.pdf) has been accepted for EMNLP 2019 as a long paper, please include it in the list. The git repo for the the paper is here https://github.com/agaralabs/transformer-drg-style-transfer

**Comment by fuzhenxin** [comment]
Congratulations! It has beed added.
