### ISSUE TITLE
Decomposing Textual Information For Style Transfer

### ISSUE THREAD

**Issue by kr0niker** [fuzhenxin/Style-Transfer-in-Text#12]
Our paper is accepted to WNGT that is co-located with EMNLP this year. It is a follow-up to "Style Transfer for Texts: Retrain, Report Errors, Compare with Rewrites" that deals with quality of information decomposition and how it is connected with the system performance.

Decomposing Textual Information For Style Transfer, WNGT, 2019, [[paper]](https://arxiv.org/abs/1909.12928)

**Comment by fuzhenxin** [comment]
Thanks and Gongratulations! The paper is added.
