### ISSUE TITLE
Is there any summary in the field of style transfer in text?

### ISSUE THREAD

**Issue by namespacegit** [fuzhenxin/Style-Transfer-in-Text#30]
Is there any summary in the field of style transfer in text?

**Comment by fuzhenxin** [comment]
I did not find a good survey paper up to now.

**Comment by namespacegit** [comment]
Thank you for your great work! This paper list is very useful.

**Comment by fuzhenxin** [comment]
Thanks!

**Comment by namespacegit** [comment]
Hi, the paper hyperlink of the paper entitled "Zero-Shot Style Transfer in Text Using Recurrent Neural Networks" is wrong, the right URL is "https://arxiv.org/abs/1711.04731v1".

**Comment by fuzhenxin** [comment]
Thanks! I have changed the url.

**Comment by qiujiangkun** [comment]
A paper at https://www.groundai.com/project/what-is-wrong-with-style-transfer-for-texts/ summarizes the field properly.

**Comment by fuzhenxin** [comment]
Thanks!
