### ISSUE TITLE
Add packages List

### ISSUE THREAD

**Issue by linonetwo** [fuzhenxin/Style-Transfer-in-Text#40]
Can you add a package list , about projects that can install via pip and use without training.

Better, can use with tensorflowjs, which don't need python in the production environment.

AFAIK, most projects just about their paper, and don't care whether other people can use their work, they just care about themselves, therefore produce useless github repos. Which is very bad in the opensource community.

**Comment by fuzhenxin** [comment]
Mismatched issue.

**Comment by linonetwo** [comment]
What mismatched with what?

**Comment by fuzhenxin** [comment]
This repo is a paper list, not a code project. And the papers in this list do not contain code that can install via pip and use without training.
