### ISSUE TITLE
Add "Efficient Reinforcement Learning for Unsupervised Controlled Text Generation" 

### ISSUE THREAD

**Issue by Bhargav5** [fuzhenxin/Style-Transfer-in-Text#42]
Hi, can you please add "Efficient Reinforcement Learning for Unsupervised Controlled Text
Generation" research paper to the list. The URL of the paper is here:https://arxiv.org/pdf/2204.07696.pdf . Thanks.

**Comment by kinghmy** [comment]
你好，来信我已收到，我会尽快处理，谢谢！

**Comment by fuzhenxin** [comment]
Added! Thanks!

**Comment by SimmerChan** [comment]
我已收到您的邮件，祝您生活愉快！

**Comment by SimmerChan** [comment]
我已收到您的邮件，祝您生活愉快！
