### ISSUE TITLE
Better category for recently added paper

### ISSUE THREAD

**Issue by sabithsn** [fuzhenxin/Style-Transfer-in-Text#46]
Hi,

Thanks a lot for maintaining this repo. It was really helpful for my research. I wanted to point out that the paper APPDIA: A Discourse-aware Transformer-based Style Transfer Model for Offensive Social Media Conversations, COLING 2022, fits better under the category Dataset or Supervised (Parallel Data). We release a dataset that contains 2K parallel pairs of offensive and style-transferred non-offensive texts. Our style transfer model is trained on this data in a supervised fashion. Our data can be found here: https://github.com/sabithsn/APPDIA-Discourse-Style-Transfer.

**Comment by fuzhenxin** [comment]
Updated. Thanks!
