### ISSUE TITLE
Accepted by EMNLP 2019 (Long) - Iterative Matching and Translation 

### ISSUE THREAD

**Issue by zhijing-jin** [fuzhenxin/Style-Transfer-in-Text#9]
Hi Zhenxin, 

Thanks a lot for compiling this list for researchers. [Unsupervised Text Attribute Transfer via Iterative Matching and Translation](https://arxiv.org/abs/1901.11333) is recently accepted by EMNLP 2019 as a long paper. Please feel free to update :).

```
- Unsupervised Text Attribute Transfer via Iterative Matching and Translation, EMNLP (long), 2019, [[paper]](https://arxiv.org/abs/1901.11333)
```

**Comment by fuzhenxin** [comment]
Thanks! I have updated the paper.

**Comment by zhijing-jin** [comment]
Thank you for adding it, Zhenxin! I also want to say a sincere thank-you for your work on curating this list. It has been so useful for us. 

**Great work :)!**

**Comment by fuzhenxin** [comment]
Thank you! I am very happy that this list is useful. Contratulations to you too!
